<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:59
 */
?>

<?php
$this->headTitle('Role');
$this->headLink()->prependStylesheet($this->basePath('css/table.min.css'));
?>

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="text-right" style="margin-bottom: 10px">
            <a class="btn btn-primary btn-md" href="<?= $this->url('foodconfig/role',['action' => 'create']); ?>">Dodaj role</a>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Role</div>
            <div class="panel-body">

                <?= $this->partial('partial/messages') ?>

                <table class="table table-striped table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nazwa</th>
                        <th>Opis</th>
                        <th>Edytuj</th>
                        <th>Usuń</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $stt = 1; ?>
                    <?php foreach ($roles as $key => $val) : ?>
                        <?php if ($val->getName() == 'admin') continue ?>
                        <tr>
                            <td><?= $stt ?></td>
                            <td><?= $this->escapeHtml($val->getName()) ?></td>
                            <td><?= $this->escapeHtml($val->getDescription()) ?></td>
                            <td>
                                <a href="<?= $this->url('foodconfig/role',[
                                    'action' => 'edit',
                                    'id' => $val->getId()
                                ]); ?>">
                                    <span class="glyphicon glyphicon-cog"></span>
                                </a>
                            </td>
                            <td>
                                <a onclick="return removeConfirm('<?= $val->getName() ?>')" href="<?= $this->url('foodconfig/role', [
                                    'action' => 'delete',
                                    'id' => $val->getId()
                                ]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </a>
                            </td>
                        </tr>
                        <?php $stt++ ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    function removeConfirm(name) {
        if (confirm("Czy napewno chcesz usunąć " + name + '?')) {
            return true;
        } else {
            return false;
        }
    }
</script>
