<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 15:02
 */
?>

<?= $this->doctype() ?>
<html lang="pl-PL">

<head>
    <?= $this->headTitle('Food Config')->setSeparator(' - ')->setAutoEscape(false) ?>

    <link rel="apple-touch-icon" sizes="180x180" href="/img/icon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/icon/favicon-16x16.png">
    <link rel="mask-icon" href="/img/icon/safari-pinned-tab.svg" color="#3e8f3e">
    <link rel="manifest" crossorigin="use-credentials" href="/img/icon/webmanifest.json">

    <?= $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('charset', 'utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendName('msapplication-TileColor', '#2b5797')
        ->appendName('theme-color', '#ffffff')
        ->appendName('title', 'Food Config - Konfigurator żywności')
        ->appendName('keywords', 'przepisy, konfigurator żywności')
        ->appendName('description', 'wyszukiwarka przepisów oparta na preferencjach użytkownika')
        ->appendName('author', 'P B')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon/favicon.ico'])
        ->prependStylesheet($this->basePath('css/layout.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-reboot.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-grid.min.css'))
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css')

    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ->prependFile($this->basePath('js/foodconfig.js'))
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js')
    ?>
</head>
<body>
    <nav id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/icon/foodconfig.svg') ?>" height="28" alt="FoodConfig"/>
                <span>&nbspFood Config</span>
            </a>
        </div>
        <div class="collapse navbar-collapse">

            <?php if($this->currentUser) : ?>
            <?= $this->navigation('admin_nav')
                ->menu()
                ->setMinDepth(0)
                ->setMaxDepth(0)
                ->setUlClass('nav navbar-nav')
                ->setAcl($this->acl)
                ->setRole($this->role) ?>
            <?php endif ?>

            <ul class="nav navbar-nav navbar-right">
                <?php if($this->currentUser) : ?>
                    <li><a href="<?= $this->url('profile',['action' => 'profile']); ?>">
                            <span class="glyphicon glyphicon-user"></span> <?= $this->currentUser ?>
                        </a>
                    </li>
                    <li><a href="<?= $this->url('foodconfig/verify',['action' => 'logout']); ?>">
                            <span class="glyphicon glyphicon-log-in"></span> Wyloguj
                        </a>
                    </li>
                <?php else : ?>
                    <li><a href="<?= $this->url('foodconfig/verify',['action' => 'login']); ?>">
                            <span class="glyphicon glyphicon-log-in"></span> Logowanie
                        </a>
                    </li>
                    <li><a href="<?= $this->url('foodconfig/verify',['action' => 'register']); ?>">
                            <span class="glyphicon glyphicon-registration-mark"></span> Rejestracja
                        </a>
                    </li>
                <?php endif ?>
            </ul>
        </div>
    </nav>

    <main class="page">
    <section class="clean-form">
        <div class="container">
            <?= $this->content ?>
        </div>
    </section>
    </main>

    <footer class="page-footer navbar-inverse">
        <div class="footer-copyright">
            &copy; <?= date('Y') ?> by
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/icon/foodconfig.svg') ?>" height="16" alt="FoodConfig"/> Food Config
            </a>- All rights reserved.
        </div>
        <div class="navbar footer-nav">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="<?= $this->url('policy',['action' => 'policy']); ?>">
                        <span class="glyphicon glyphicon glyphicon-lock"></span> Polityka prywatności</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= $this->url('contact',['action' => 'contact']); ?>">
                        <span class="glyphicon glyphicon-earphone"></span> Kontakt</a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>