<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:55
 */
?>

<?php
$this->headTitle('Zmiana hasła');
$form->setAttribute('action', $this->url('foodconfig/verify', [
    'action' => 'forgot'
]));
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->partial('partial/messages') ?>
        <div class="panel panel-default">
            <div class="panel-heading">Zresetuj hasło</div>
            <div class="panel-body">
                <?= $this->form()->openTag($form) ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('email')) ?>
                    <?= $this->formElement($form->get('email')) ?>
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('captcha')) ?>
                    <?= $this->formElement($form->get('captcha')) ?>
                    <?= $this->formElementErrors($form->get('captcha')) ?>
                </div>

                <?= $this->formElement($form->get('csrf')) ?>

                <div class="form-group">
                    <?= $this->formElement($form->get('submit')) ?>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>