<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:56
 */
?>

<?php
$this->headTitle('Rejestracja');
$this->headScript()->prependFile($this->basePath('js/register.js'));
$this->headScript()->prependFile('https://unpkg.com/sweetalert/dist/sweetalert.min.js');
$form->setAttribute('action', $this->url('foodconfig/verify', [
    'action' => 'register'
]));
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?php if($test['error']) { ?>
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?= $test['error']; ?></li>
            </ul>
        </div>
        <?php } ?>
        <?= $this->partial('partial/messages') ?>
        <div class="panel panel-default">
            <div class="panel-heading">Rejestracja</div>
            <div class="panel-body">
                <?= $this->form()->openTag($form) ?>
                <div class="form-group">
                    <img src="<?= $this->basePath('img/avatar/default.png') ?>" width="140" height="140" id="uploadPreview" class="center-block img-circle">
                    <?= $this->formElement($form->get('avatar')) ?>
                    <?= $this->formElementErrors($form->get('avatar')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('name')) ?>
                    <?= $this->formElementErrors($form->get('name')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('surname')) ?>
                    <?= $this->formElementErrors($form->get('surname')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('email')) ?>
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('password_one')) ?>
                    <?= $this->formElementErrors($form->get('password_one')) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('password_two')) ?>
                    <?= $this->formElementErrors($form->get('password_two')) ?>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="text-left">
                                <?= $this->formElement($form->get('usershow')) ?>
                                <span>Publiczny profil ?</span>
                            </div>
                        </div>
                    </div>
                </div>

                <?= $this->formElement($form->get('csrf')) ?>
                <div class="form-group">
                    <?= $this->formElement($form->get('submit')) ?>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>