<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:59
 */

$form->setAttribute('action', $this->url('foodconfig/user', [
    'action' => 'store'
]));
$form->get('submit')->setValue('Dalej');
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Dodaj Użytkownika</div>
            <div class="panel-body">
                <p>Proszę wypełnić i kliknąć <i>Dalej</i></p>

                <?= $this->form()->openTag($form); ?>

                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('surname')); ?>
                    <?= $this->formElement($form->get('surname')); ?>
                    <?= $this->formElementErrors($form->get('surname')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('avatar')); ?>
                    <?= $this->formElement($form->get('avatar')); ?>
                    <?= $this->formElementErrors($form->get('avatar')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('usershow')); ?>
                    <?= $this->formElement($form->get('usershow')); ?>
                    <?= $this->formElementErrors($form->get('usershow')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('password')); ?>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('active')); ?>
                    <?= $this->formElement($form->get('active')); ?>
                    <?= $this->formElementErrors($form->get('active')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('level')); ?>
                    <?= $this->formElement($form->get('level')); ?>
                    <?= $this->formElementErrors($form->get('level')); ?>
                </div>

                <?= $this->formElement($form->get('submit')); ?>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>