<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 15:01
 */
?>

<?php
$this->headTitle('Użytkownicy');
$this->headLink()->prependStylesheet($this->basePath('css/table.min.css'));
?>

<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <?php if($this->user_1->getLevel() == 2) : ?>
            <div class="text-right" style="margin-bottom: 10px">
                <a class="btn btn-primary btn-md" href="<?= $this->url('foodconfig/verify',['action' => 'register']); ?>">Dodaj użytkownika</a>
            </div>
        <?php endif ?>
        <div class="panel panel-default">
            <div class="panel-heading">Użytkownicy</div>
            <div class="panel-body">

                <?= $this->partial('partial/messages') ?>

                <table class="table table-striped table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nazwa</th>
                        <?php if($this->user_1->getLevel() == 2) : ?>
                            <th>Email</th>
                            <th>Edytuj</th>
                            <th>Usuń</th>
                        <?php endif ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $stt = 1; ?>
                    <?php foreach ($user as $key => $val) : ?>

                        <tr>
                            <td><?= $stt ?></td>
                            <td><?= $this->escapeHtml($val->getName() . ' ' . $val->getSurname()) ?></td>
                            <?php if($this->user_1->getLevel() == 2) : ?>
                                <td><?= $this->escapeHtml($val->getEmail()) ?></td>
                                <td>
                                    <a href="<?= $this->url('foodconfig/user',[
                                        'action' => 'edit',
                                        'id' => $val->getId()
                                    ]); ?>">
                                        <span class="glyphicon glyphicon-cog"></span>
                                    </a>
                                </td>
                                <td>
                                    <a onclick="return removeConfirm('<?= $val->getName() . ' ' . $val->getSurname() ?>')" href="<?= $this->url('foodconfig/user', [
                                        'action' => 'delete',
                                        'id' => $val->getId()
                                    ]); ?>">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            <?php endif ?>
                        </tr>
                        <?php $stt++ ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php if($this->user_1->getLevel() == 2) : ?>
    <script>
        function removeConfirm(name) {
            if (confirm("Chcesz usunąć użytkownika " + name + '?')) {
                return true;
            } else {
                return false;
            }
        }
    </script>
<?php endif ?>