<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:56
 */
?>

<?php
$this->headTitle('Kontakt');
$form->setAttribute('action', $this->url('contact', [
    'action' => 'contact'
]));
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->partial('partial/messages') ?>
        <div class="panel panel-default">
            <div class="panel-heading">Wyślij wiadomość do administratora</div>
            <div class="panel-body">
                <?= $this->form()->openTag($form) ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('email')) ?>
                    <?= $this->formElement($form->get('email')) ?>
                    <?= $this->formElementErrors($form->get('email')) ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('message')) ?>
                    <?= $this->formElement($form->get('message')) ?>
                    <?= $this->formElementErrors($form->get('message')) ?>
                </div>

                <div class="form-group" style="box-sizing: content-box">
                    <?= $this->formLabel($form->get('captcha')) ?>
                    <?= $this->formElement($form->get('captcha')) ?>
                    <?= $this->formElementErrors($form->get('captcha')) ?>
                </div>

                <?= $this->formElement($form->get('csrf')) ?>

                <div class="form-group">
                    <?= $this->formElement($form->get('submit')) ?>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>
