<?php
/**
 * Created by PhpStorm.
 * User: piotrbec
 * Date: 2019-04-03
 * Time: 14:56
 */
?>

<?php
$this->headTitle('Polityka Prywatności');
?>

<h2 style="text-align: center">Polityka Prywatności</h2>
<span style="width: 100%; text-align: center" class="glyphicon glyphicon-asterisk"></span>
<div id="lipsum">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor felis in velit dictum feugiat. Nunc ut nulla sed sapien molestie sodales. Integer pulvinar faucibus turpis, in lobortis risus condimentum ac. Vivamus id aliquam odio, imperdiet ultrices ex. Praesent vitae velit sed magna congue tristique. Morbi dictum eros non felis varius ultricies. Ut commodo mauris eleifend lacinia consectetur. Aliquam erat volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel libero ut orci commodo rhoncus. Integer sodales bibendum mauris, sed commodo purus mollis venenatis. Nullam ac augue eu mauris efficitur eleifend. Suspendisse potenti. Vestibulum in lectus sollicitudin, lobortis risus et, tincidunt sem. Proin odio tellus, feugiat luctus nisl non, condimentum consequat diam. Maecenas a ultrices metus, cursus vulputate lectus.
    </p>
    <p>
        Duis pharetra nisl vitae risus ornare consequat. Phasellus malesuada imperdiet tempor. Ut eu condimentum sapien, a pharetra libero. Suspendisse massa diam, condimentum in risus id, consectetur tempus risus. Sed in risus ac leo accumsan cursus sed a purus. Duis commodo aliquam augue sit amet ullamcorper. Curabitur hendrerit purus et purus maximus, vitae efficitur est sollicitudin. Nullam pellentesque in lacus ornare tincidunt.
    </p>
    <p>
        Praesent cursus, metus rhoncus luctus fermentum, enim diam rutrum dolor, vel mattis nunc nibh non purus. Cras venenatis mattis ex non convallis. Sed vehicula consectetur vestibulum. Phasellus sollicitudin diam sed magna vestibulum, at hendrerit ipsum posuere. Duis vehicula nulla eu sagittis aliquet. Donec quis nibh mattis, dictum felis ut, convallis tortor. Aenean lectus ligula, vestibulum non nunc eget, ullamcorper ornare odio.
    </p>
    <p>
        In suscipit nibh sit amet magna iaculis, id ornare tellus pretium. Aenean placerat diam quis porta vestibulum. Nunc cursus ultricies tellus, et maximus ligula placerat ut. In scelerisque libero ut justo ultrices, et porttitor tortor viverra. Etiam efficitur nunc eu pretium congue. Maecenas dignissim justo id risus ullamcorper, sed dictum nunc imperdiet. In ac mattis metus. Aliquam vulputate eleifend auctor. Praesent non eros magna. In vel libero a augue luctus convallis vitae a massa. Suspendisse potenti.
    </p>
    <p>
        Phasellus nibh magna, ornare ac lectus at, feugiat laoreet odio. Nulla viverra elementum eros et condimentum. Vivamus vel ipsum risus. Ut dapibus, velit at pharetra consequat, orci lacus rhoncus diam, venenatis cursus velit quam at nulla. Pellentesque efficitur vel eros consectetur vulputate. Nullam magna justo, pulvinar eget volutpat sit amet, mattis a nunc. Praesent lobortis interdum efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ultricies dui nisl, nec porttitor arcu suscipit nec.
    </p>
    <p>
        Mauris vel augue sed enim rutrum tincidunt. Integer imperdiet, eros sit amet convallis feugiat, ante nulla eleifend quam, ut efficitur lectus erat eget nisl. Mauris non justo porta nulla pretium auctor. Mauris arcu velit, pretium ac volutpat id, aliquet at nisl. Praesent porttitor ullamcorper sapien porttitor tempor. Etiam maximus sapien non sapien consectetur, eget imperdiet velit placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent id aliquet dolor. Morbi sapien leo, dapibus rhoncus est eget, dapibus cursus metus. Nullam nec est eu libero ultricies facilisis. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi molestie leo non orci dapibus, eu tincidunt sapien efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla sed erat quis ipsum tincidunt semper ac id justo.
    </p>
</div>
<span style="width: 100%; text-align: center" class="glyphicon glyphicon-asterisk"></span>